const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.png',
      price: 90,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 7,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Other Shirt',
      slug: 'other-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpeg',
      price: 120,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 4,
      countInStock: 5,
      description: 'Another popular shirt',
    },
    {
      name: '3rd Shirt',
      slug: 'third-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpeg',
      price: 150,
      brand: 'Nike',
      rating: 4.8,
      numReviews: 8,
      countInStock: 9,
      description: 'Best popular shirt',
    },
    {
      name: 'Cool Pants',
      slug: 'cool-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 250,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 3,
      countInStock: 32,
      description: 'Cool pair of pants',
    },
    {
      name: '2nd Pants',
      slug: 'second-pants',
      category: 'Pants',
      image: '/images/pants2.jpeg',
      price: 300,
      brand: 'Adidas',
      rating: 4.3,
      numReviews: 4,
      countInStock: 20,
      description: 'Best popular pants',
    },
  ],
};

export default data;
